# This is a Python file for all xpaths in the rpm form.

employeeName = '/html/body/div/div/div[1]/span/input'
summary = '/html/body/div/div/div[3]/span[2]/textarea'
department = '/html/body/div/div/div[5]/span/span/select'
salary = '/html/body/div/div/div[6]/span/input'
addressLat = '/html/body/div/div/div[7]/span/label[1]/input'
addressLong = '/html/body/div/div/div[7]/span/label[2]/input'
workLocation = '/html/body/div/div/div[8]/span/span/select'
date = '/html/body/div/div/div[10]/span/span/input'
active = '/html/body/div/div/div[12]/span/input[1]'
length = '/html/body/div/div/div[15]/span[2]/div/table/tbody/tr[2]/td[2]/div/div/div/span/input'
lengthUnit = '/html/body/div/div/div[15]/span[2]/div/table/tbody/tr[2]/td[2]/div/div/div/span/select'
width = '/html/body/div/div/div[15]/span[2]/div/table/tbody/tr[2]/td[3]/div/div/div/span/input'
widthUnit = '/html/body/div/div/div[15]/span[2]/div/table/tbody/tr[2]/td[3]/div/div/div/span/select'
color = '/html/body/div/div/div[15]/span[2]/div/table/tbody/tr[2]/td[4]/div/div/div/input'
brand1 = '/html/body/div/div/div[16]/span[2]/div/table/tbody/tr[2]/td[2]/div/div/div/input'
brand2 = '/html/body/div/div/div[16]/span[2]/div/table/tbody/tr[3]/td[2]/div/div/div/input'
model1 = '/html/body/div/div/div[16]/span[2]/div/table/tbody/tr[2]/td[3]/div/div/div/input'
model2 = '/html/body/div/div/div[16]/span[2]/div/table/tbody/tr[3]/td[3]/div/div/div/input'
modelYear1 = '/html/body/div/div/div[16]/span[2]/div/table/tbody/tr[2]/td[4]/div/div/div/input'
modelYear2 = '/html/body/div/div/div[16]/span[2]/div/table/tbody/tr[3]/td[4]/div/div/div/input'
trim1 = '/html/body/div/div/div[16]/span[2]/div/table/tbody/tr[2]/td[5]/div/div/div/input'
trim2 = '/html/body/div/div/div[16]/span[2]/div/table/tbody/tr[3]/td[5]/div/div/div/input'
carColor1 = '/html/body/div/div/div[16]/span[2]/div/table/tbody/tr[2]/td[6]/div/div/div/input'
carColor2 = '/html/body/div/div/div[16]/span[2]/div/table/tbody/tr[3]/td[6]/div/div/div/input'
license1 = '/html/body/div/div/div[16]/span[2]/div/table/tbody/tr[2]/td[7]/div/div/div/input'
license2 = '/html/body/div/div/div[16]/span[2]/div/table/tbody/tr[3]/td[7]/div/div/div/input'
submit = '/html/body/div/div/div[18]/form/button'

